CREATE TABLE ROOM_TYPE
(
   TYPE_ID              INT NOT NULL AUTO_INCREMENT,
   NAME                 VARCHAR(50),
   TYPE_CONTENT         VARCHAR(200),
   PRIMARY KEY (TYPE_ID)
);
ALTER TABLE ROOM ADD COLUMN TYPE_ID INT;
ALTER TABLE SCHOOLTERM ADD COLUMN START_DATE DATE;
ALTER TABLE SCHOOLTERM ADD COLUMN END_DATE DATE;
ALTER TABLE ROOM ADD CONSTRAINT FK_TYPE_ID_ROOM FOREIGN KEY (TYPE_ID)
      REFERENCES ROOM_TYPE (TYPE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;